UBOOT_OUT := $(TARGET_OUT_INTERMEDIATES)/UBOOT

TARGET_UBOOT := $(UBOOT_OUT)/RK30xxLoader(L)_V0.02_PRELIMINARY_EMMC_ONLY.bin

$(TARGET_UBOOT): $(UBOOT_OUT)
	$(MAKE) -C u-boot O=../$(UBOOT_OUT) rk30xx

$(UBOOT_OUT):
	mkdir -p $(UBOOT_OUT)

droidcore: $(TARGET_UBOOT)

.PHONY: $(TARGET_UBOOT)
